language: dart
dart:
#- stable
#- beta
#- dev

dart_task:
- test: --platform vm
#- test: --platform chrome
- dartfmt

# Warnings are fatal, but we only analyze the lib/ directory.
- dartanalyzer: --fatal-warnings lib